import React, { useState } from 'react';
import {
  Calendar,
  Check,
  CheckCircle2,
  Copy,
  Download,
  FileSpreadsheet,
  FileText,
  Globe,
  MessageSquare,
  Send,
  Sparkles,
  X,
} from 'lucide-react';
import { Meeting } from '../types.js';

interface ExportModalProps {
  meeting: Meeting;
  isOpen: boolean;
  onClose: () => void;
  onShowToast: (msg: string, type?: 'success' | 'info') => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  meeting,
  isOpen,
  onClose,
  onShowToast,
}) => {
  const [copiedMd, setCopiedMd] = useState(false);
  const [webhookUrl, setWebhookUrl] = useState('');
  const [webhookPlatform, setWebhookPlatform] = useState<'slack' | 'teams' | 'custom'>('slack');
  const [isSendingWebhook, setIsSendingWebhook] = useState(false);
  const [webhookResult, setWebhookResult] = useState<string | null>(null);

  if (!isOpen) return null;

  // Generate markdown report
  const generateMarkdown = () => {
    let md = `# 📋 Meeting Action Items: ${meeting.title}\n`;
    md += `**Date:** ${meeting.date} | **Duration:** ${meeting.duration_minutes}m | **Participants:** ${meeting.participants.join(', ')}\n\n`;
    md += `## 📝 Summary\n${meeting.summary}\n\n`;

    md += `## ✅ Action Items & Commitments\n`;
    meeting.action_items.forEach((item, idx) => {
      const check = item.status === 'completed' ? '[x]' : '[ ]';
      md += `${idx + 1}. ${check} **${item.task_description}**\n`;
      md += `   - **Owner:** @${item.owner} | **Deadline:** ${item.deadline} | **Priority:** ${item.priority.toUpperCase()} | **Confidence:** ${Math.round(item.confidence_score * 100)}%\n`;
      if (item.source_quote) {
        md += `   - *Source Quote:* "${item.source_quote}"\n`;
      }
    });

    if (meeting.executive_summary?.key_decisions?.length) {
      md += `\n## 🎯 Key Decisions\n`;
      meeting.executive_summary.key_decisions.forEach((dec) => {
        md += `- ${dec}\n`;
      });
    }

    md += `\n---\n*Generated by PulseAction AI*`;
    return md;
  };

  const handleCopyMarkdown = async () => {
    const md = generateMarkdown();
    try {
      await navigator.clipboard.writeText(md);
      setCopiedMd(true);
      onShowToast('Markdown report copied to clipboard!', 'success');
      setTimeout(() => setCopiedMd(false), 2500);
    } catch (err) {
      onShowToast('Failed to copy to clipboard', 'info');
    }
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(meeting, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `${meeting.title.replace(/[^a-z0-9]/gi, '_')}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
    onShowToast('Downloaded JSON dataset', 'success');
  };

  const handleDispatchWebhook = async () => {
    setIsSendingWebhook(true);
    setWebhookResult(null);
    try {
      const res = await fetch('/api/webhook/simulate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          meeting_id: meeting.id,
          platform: webhookPlatform,
          webhook_url: webhookUrl.trim() || undefined,
        }),
      });
      const data = await res.json();
      if (data.success) {
        setWebhookResult(data.message || 'Notification dispatched successfully!');
        onShowToast('Webhook notification delivered!', 'success');
      } else {
        setWebhookResult(data.message || 'Webhook simulation completed.');
      }
    } catch (err: any) {
      setWebhookResult(`Error: ${err.message}`);
    } finally {
      setIsSendingWebhook(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-200">
      <div className="relative w-full max-w-2xl rounded-2xl border border-slate-800 bg-slate-900 p-6 sm:p-8 space-y-6 shadow-2xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between pb-4 border-b border-slate-800">
          <div className="space-y-1">
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-violet-400" />
              <span>Magic Export & Workflow Integrations</span>
            </h3>
            <p className="text-xs text-slate-400">
              Export tasks to calendar apps, Slack/Teams channels, or tabular datasets.
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-slate-200 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* 1. Quick Export Buttons Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
          {/* Calendar .ICS Export */}
          <a
            href={`/api/meetings/${meeting.id}/export/ics`}
            download
            onClick={() => onShowToast('Downloading iCalendar (.ics) file...', 'info')}
            className="p-4 rounded-xl bg-slate-950/80 hover:bg-slate-950 border border-slate-800 hover:border-violet-500/50 transition-all flex items-start gap-3 group text-left"
          >
            <div className="p-2.5 rounded-lg bg-violet-500/10 text-violet-400 group-hover:bg-violet-500/20 group-hover:scale-105 transition-all">
              <Calendar className="w-5 h-5" />
            </div>
            <div>
              <div className="font-semibold text-xs text-slate-200 group-hover:text-white flex items-center gap-1.5">
                <span>Google & Apple Calendar</span>
                <Download className="w-3 h-3 text-slate-500" />
              </div>
              <p className="text-[11px] text-slate-400 mt-1">
                Download .ics events with dates, owners, and quotes.
              </p>
            </div>
          </a>

          {/* Markdown Copy */}
          <button
            onClick={handleCopyMarkdown}
            className="p-4 rounded-xl bg-slate-950/80 hover:bg-slate-950 border border-slate-800 hover:border-emerald-500/50 transition-all flex items-start gap-3 group text-left cursor-pointer"
          >
            <div className="p-2.5 rounded-lg bg-emerald-500/10 text-emerald-400 group-hover:bg-emerald-500/20 group-hover:scale-105 transition-all">
              {copiedMd ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
            </div>
            <div>
              <div className="font-semibold text-xs text-slate-200 group-hover:text-white flex items-center gap-1.5">
                <span>{copiedMd ? 'Copied to Clipboard!' : 'Copy Markdown Report'}</span>
              </div>
              <p className="text-[11px] text-slate-400 mt-1">
                Formatted checklist ready for Slack, Teams, or Email.
              </p>
            </div>
          </button>

          {/* CSV Spreadsheet Export */}
          <a
            href={`/api/meetings/${meeting.id}/export/csv`}
            download
            onClick={() => onShowToast('Downloading tasks CSV spreadsheet...', 'info')}
            className="p-4 rounded-xl bg-slate-950/80 hover:bg-slate-950 border border-slate-800 hover:border-sky-500/50 transition-all flex items-start gap-3 group text-left"
          >
            <div className="p-2.5 rounded-lg bg-sky-500/10 text-sky-400 group-hover:bg-sky-500/20 group-hover:scale-105 transition-all">
              <FileSpreadsheet className="w-5 h-5" />
            </div>
            <div>
              <div className="font-semibold text-xs text-slate-200 group-hover:text-white flex items-center gap-1.5">
                <span>Export CSV Spreadsheet</span>
                <Download className="w-3 h-3 text-slate-500" />
              </div>
              <p className="text-[11px] text-slate-400 mt-1">
                Columns: Task, Owner, Deadline, Confidence, Risk, Quote.
              </p>
            </div>
          </a>

          {/* JSON Export */}
          <button
            onClick={handleDownloadJSON}
            className="p-4 rounded-xl bg-slate-950/80 hover:bg-slate-950 border border-slate-800 hover:border-purple-500/50 transition-all flex items-start gap-3 group text-left cursor-pointer"
          >
            <div className="p-2.5 rounded-lg bg-purple-500/10 text-purple-400 group-hover:bg-purple-500/20 group-hover:scale-105 transition-all">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="font-semibold text-xs text-slate-200 group-hover:text-white flex items-center gap-1.5">
                <span>Full JSON Archive</span>
                <Download className="w-3 h-3 text-slate-500" />
              </div>
              <p className="text-[11px] text-slate-400 mt-1">
                Raw transcript segments, diarization turns, & metadata.
              </p>
            </div>
          </button>
        </div>

        {/* 2. Webhook Dispatch & Notification Section */}
        <div className="rounded-xl border border-slate-800 bg-slate-950/60 p-5 space-y-4">
          <div className="flex items-center justify-between">
            <h4 className="font-bold text-xs uppercase tracking-wider text-slate-300 flex items-center gap-2">
              <MessageSquare className="w-4 h-4 text-violet-400" />
              <span>Slack / Teams Webhook Dispatcher</span>
            </h4>
            <span className="text-[11px] text-slate-400">Live or Simulated test</span>
          </div>

          <div className="space-y-3">
            <div className="grid grid-cols-3 gap-2">
              <button
                type="button"
                onClick={() => setWebhookPlatform('slack')}
                className={`py-1.5 rounded-lg text-xs font-semibold border transition-all ${
                  webhookPlatform === 'slack'
                    ? 'bg-violet-600 text-white border-violet-500'
                    : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200'
                }`}
              >
                Slack #action-items
              </button>
              <button
                type="button"
                onClick={() => setWebhookPlatform('teams')}
                className={`py-1.5 rounded-lg text-xs font-semibold border transition-all ${
                  webhookPlatform === 'teams'
                    ? 'bg-violet-600 text-white border-violet-500'
                    : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200'
                }`}
              >
                Microsoft Teams
              </button>
              <button
                type="button"
                onClick={() => setWebhookPlatform('custom')}
                className={`py-1.5 rounded-lg text-xs font-semibold border transition-all ${
                  webhookPlatform === 'custom'
                    ? 'bg-violet-600 text-white border-violet-500'
                    : 'bg-slate-900 text-slate-400 border-slate-800 hover:text-slate-200'
                }`}
              >
                Custom Webhook URL
              </button>
            </div>

            {webhookPlatform === 'custom' && (
              <div>
                <input
                  type="url"
                  value={webhookUrl}
                  onChange={(e) => setWebhookUrl(e.target.value)}
                  placeholder="https://hooks.slack.com/services/... or https://outlook.office.com/webhook/..."
                  className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-lg text-xs text-slate-200 placeholder-slate-600 focus:outline-none focus:border-violet-500"
                />
              </div>
            )}

            <div className="flex items-center justify-between pt-1">
              <span className="text-[11px] text-slate-400">
                Sends payload with {meeting.action_items.length} tasks to channel
              </span>
              <button
                type="button"
                disabled={isSendingWebhook}
                onClick={handleDispatchWebhook}
                className="inline-flex items-center gap-1.5 px-4 py-1.5 rounded-lg bg-violet-600 hover:bg-violet-500 text-white text-xs font-semibold transition-all disabled:opacity-50 cursor-pointer"
              >
                {isSendingWebhook ? (
                  <>
                    <div className="w-3 h-3 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                    <span>Sending...</span>
                  </>
                ) : (
                  <>
                    <Send className="w-3.5 h-3.5" />
                    <span>Dispatch Notification</span>
                  </>
                )}
              </button>
            </div>

            {webhookResult && (
              <div className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-xs text-slate-300 flex items-start gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                <span>{webhookResult}</span>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="flex justify-end pt-2">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg bg-slate-800 hover:bg-slate-700 text-xs font-medium text-slate-300 hover:text-white transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
